<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<LangVersion>12</LangVersion>
		<IsPackable>false</IsPackable>
		<IsTestProject>true</IsTestProject>

		<EnableNETAnalyzers>false</EnableNETAnalyzers>
		<EnforceCodeStyleInBuild>false</EnforceCodeStyleInBuild>
		<NoWarn>$(NoWarn);SA1507;SA1210;SA1202;SA1413;SA1116;SA1117;SA1025;SA1316;SA1402;SK1200;IDE0008;IDE0005;IDE0021;CA1724</NoWarn>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\src\CarRental.Api\CarRental.Api.csproj" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.NET.Test.Sdk" />
		<PackageReference Include="xunit" />
		<PackageReference Include="xunit.runner.visualstudio">
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
			<PrivateAssets>all</PrivateAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
		<PackageReference Include="Testcontainers.PostgreSql" />
		<PackageReference Include="FluentAssertions" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design">
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" />
	</ItemGroup>

</Project>